from pydantic import BaseModel
from typing import Optional

class ChatRequest(BaseModel):
    systemPrompt: str
    userPrompt: str
    expectedOutput: str
    model: str
class CreateMetrics(BaseModel):
    modelName: str
    modelVersion: str
    modelType: str
    modelProvider: str
    modelConfig: str
    systemPrompt: str
    userPrompt: str
    expectedOutput: str
    relevanceScore: float
    accuracyScore: float
    clarityScore: float
    coherenceScore: float
    creativityScore: float
    alignmentScore: float
    response: str
    evaluation: str
    evaluationScore: float
    hallucinationScore: float
    evaluationFeedback: str
    hallucinationFeedback: str
    testType: str
class RetrieveMetrics(BaseModel):
    id: str
    modelName: str
    modelVersion: str
    modelType: str
    modelProvider: str
    modelConfig: str
    systemPrompt: str
    userPrompt: str
    expectedOutput: str
    relevanceScore: float
    accuracyScore: float
    clarityScore: float
    coherenceScore: float
    creativityScore: float
    alignmentScore: float
    response: str
    evaluation: str
    evaluationScore: float
    evaluationFeedback: str
    hallucinationScore: float
    hallucinationFeedback: str
    testType: str